import { db } from "../db";
import { leads, messages, conversations, contacts, agentTasks } from "../../drizzle/schema";
import { eq, and, gte, lte, count } from "drizzle-orm";

export interface ReportFilter {
  workspaceId: string;
  startDate?: Date;
  endDate?: Date;
  campaignId?: string;
}

export interface ReportingMetrics {
  leadsDiscovered: number;
  leadsResearched: number | null; // null indicates not available yet (no research agent/flag implemented)
  awaitingQualification: number;
  messagesSent: number;
  repliesReceived: number;
  followUpTasksCompleted: number;
  meetingsBooked: number | null; // null indicates not available yet
}

/**
 * Retrieves core reporting and analytics metrics for a given workspace.
 *
 * Filters:
 * - workspaceId: MUST be provided to enforce tenant isolation.
 * - startDate / endDate: filters by creation/sent dates where applicable.
 * - campaignId: filters leads by campaign_id.
 */
export async function getReportingMetrics(filter: ReportFilter): Promise<ReportingMetrics> {
  const { workspaceId, startDate, endDate, campaignId } = filter;

  if (!workspaceId) {
    throw new Error("workspaceId is required for reporting metrics");
  }

  // Helper to build date/workspace conditions for leads
  const buildLeadConditions = () => {
    const conditions = [eq(leads.workspace_id, workspaceId)];
    if (startDate) conditions.push(gte(leads.created_at, startDate));
    if (endDate) conditions.push(lte(leads.created_at, endDate));
    if (campaignId) conditions.push(eq(leads.campaign_id, campaignId));
    return and(...conditions);
  };

  // 1. Leads Discovered (total leads matching filters)
  const leadsResult = await db.select({ count: count() }).from(leads).where(buildLeadConditions());
  const leadsDiscovered = leadsResult[0]?.count ?? 0;

  // 2. Awaiting Qualification (leads with status = 'qualification_pending' or similar intent mapping)
  // Note: A true "qualified" count depends on the future Qualification agent (Issue #8).
  const qualifiedConditions = [
    eq(leads.workspace_id, workspaceId),
    eq(leads.status, "qualification_pending"),
  ];
  if (startDate) qualifiedConditions.push(gte(leads.created_at, startDate));
  if (endDate) qualifiedConditions.push(lte(leads.created_at, endDate));
  if (campaignId) qualifiedConditions.push(eq(leads.campaign_id, campaignId));

  const qualifiedResult = await db
    .select({ count: count() })
    .from(leads)
    .where(and(...qualifiedConditions));
  const awaitingQualification = qualifiedResult[0]?.count ?? 0;

  // 3 & 4. Messages Sent & Replies Received
  // Note: We cannot easily filter messages by campaign_id without a complex join through conversations -> contacts -> leads.
  // Note: "messagesSent" currently includes Drafts generated by the Conversation Agent since migration 0003
  // (which adds messages.status) is not applied yet. This incorrectly inflates the "sent" count with unsent drafts.
  // Date filters apply to the message's sent_at timestamp.
  const buildMessageConditions = (direction: "inbound" | "outbound") => {
    const conditions = [eq(messages.workspace_id, workspaceId), eq(messages.direction, direction)];
    if (startDate) conditions.push(gte(messages.sent_at, startDate));
    if (endDate) conditions.push(lte(messages.sent_at, endDate));
    return and(...conditions);
  };

  const outboundResult = await db
    .select({ count: count() })
    .from(messages)
    .where(buildMessageConditions("outbound"));
  const messagesSent = outboundResult[0]?.count ?? 0;

  const inboundResult = await db
    .select({ count: count() })
    .from(messages)
    .where(buildMessageConditions("inbound"));
  const repliesReceived = inboundResult[0]?.count ?? 0;

  // 5. Follow-up Activity
  // We don't have a specific follow-ups table. We can measure follow-up activity by counting agentTasks
  // with agent_type = 'follow_up' that are completed.
  const buildTaskConditions = () => {
    const conditions = [
      eq(agentTasks.workspace_id, workspaceId),
      eq(agentTasks.agent_type, "follow_up"),
      eq(agentTasks.status, "completed"),
    ];
    if (startDate) conditions.push(gte(agentTasks.created_at, startDate));
    if (endDate) conditions.push(lte(agentTasks.created_at, endDate));
    return and(...conditions);
  };

  const followUpResult = await db
    .select({ count: count() })
    .from(agentTasks)
    .where(buildTaskConditions());
  const followUpTasksCompleted = followUpResult[0]?.count ?? 0;

  return {
    leadsDiscovered,
    leadsResearched: null, // Metric not available yet; no research flag/table in schema
    awaitingQualification,
    messagesSent,
    repliesReceived,
    followUpTasksCompleted,
    meetingsBooked: null, // Metric not available yet; no meetings table in schema
  };
}
